### ISSUE TITLE
Not Finding atsynedit Dep

### ISSUE THREAD

**Issue by levone1** [Alexey-T/ATSynEdit_Cmp#1]
New to Lazarus, so maybe missing something obvious... I am building deps for CudaText-1.165.2, and using lazbuild on cli. When trying to build atsynedit_cmp, I get 
`Error: (lazbuild) Broken dependency: ats
ynedit_cmp_package 2.0->atsynedit_packag
e`
Other paxkages built fine, and I got similar message with other packages, (e.g. Building atsynedit complained about not having atflatcontrols), but was solved by copying package folder, (atflatcontrol folder with built libs), to the current folder, and building again, and was successful. However, here, it's not working. I have atsynedit_package folder with built libs in atsynedit_cmp folder, and still same error.

My command is `lazbuild -B atsynedit_cmp_package.lpk`

Thanks

**Comment by Alexey-T** [comment]
I did not try to call lazbuild directly ! I tried only the CudaText_up which calls lazbuild. You can find it at the same GitHub account

Cudatext_up downloads all latest packages

**Comment by levone1** [comment]
> I did not try to call lazbuild directly ! I tried only the CudaText_up which calls lazbuild. You can find it at the same GitHub account
> 
> Cudatext_up downloads all latest packages

Thanks, I didn't see that... Ran the scriot, and got this error:
- Error: (5000) Identifier not found "IM_Context_Set_Cursor_Pos"

Output finished with 
```
atsynedit.pas(10055) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppca64 returned an error exitcode
Error: (lazarus) Compile package atsynedit_package 2.5: stopped with exit code 1
Error: (lazbuild) atsynedit_package 2.5 compilation failed
Error: (lazbuild) Broken dependency: atsynedit_cmp_package 2.0->atsynedit_package
Error: (lazbuild) Broken dependency: econtrol_package 2.1->atsynedit_package
Error: (lazbuild) Broken dependency: atsynedit_ex_package 2.0->econtrol_package
Error: (lazbuild) Broken dependency: atsynedit_cmp_package
```

Whole output is here - https://pastebin.com/LbZqWKKD

**Comment by levone1** [comment]
Note - my setup is somewhat hacky/niche-y, so could be just me... (SailfishOS mobile with lots of unofficial tweaks/hacks)...

**Comment by Alexey-T** [comment]
That error is here

atsynedit.pas
line 8482
Error: (5000) Identifier not found "IM_Context_Set_Cursor_Pos"

to solve it

1) disable (comment) the line in atsynedit.pas
`    {$define GTK2_IME_CODE}`

or

2) enable the define
```
{$IFDEF WITH_GTK2_IM}
procedure IM_Context_Set_Cursor_Pos(X, Y: gint);
{$ENDIF}
```
in the file lazarus/lcl/interfaces/gtk2/gtk2globals.pp

by enabling the WITH_GTK2_IM in the IDE, and rebuild the IDE.

**Comment by Alexey-T** [comment]
How i enabled that 'define' in IDE

![Screenshot from 2022-06-05 21-13-11](https://user-images.githubusercontent.com/4154978/172064546-2657824f-3ca9-4e5e-81db-5f54804a1862.png)

**Comment by levone1** [comment]
> How i enabled that 'define' in IDE
> 
> ![Screenshot from 2022-06-05 21-13-11](https://user-images.githubusercontent.com/4154978/172064546-2657824f-3ca9-4e5e-81db-5f54804a1862.png)



> 

Thank you - here's error log after commenting line...

https://pastebin.com/i1jN2Z1n

**Comment by Alexey-T** [comment]
new error is:

/home/defaultuser/.local/share/lazarus/lcl/interfaces/lcl.pas(11,3) Fatal: (10022) Can't find unit AllLCLIntfUnits used by LCL

this means that Laz IDE is not property installed. you should use FpcUpDeluxe to install the Laz IDE.

**Comment by Alexey-T** [comment]
also I recommend to update FPC to '3.2.2 fixes',
you have

Free Pascal Compiler version 3.2.2 [2021/05/23] for aarch64

**Comment by levone1** [comment]
> also I recommend to update FPC to '3.2.2 fixes', you have
> 
> Free Pascal Compiler version 3.2.2 [2021/05/23] for aarch64

Thanks... I ran it, and got errors about files not found, ending with makefile not found... Seems lije it didn't download everything properly... I'll poke around a bit and see what I can figure out...

![Screenshot_20220606_002](https://user-images.githubusercontent.com/43003405/172250283-e98a34a7-d5ef-48ba-a82b-8e97d9dd7bc5.png)
![Screenshot_20220606_001](https://user-images.githubusercontent.com/43003405/172250288-0758a2ec-6c82-4423-8188-84de384456cd.png)

**Comment by Alexey-T** [comment]
Maybe you can ask for support here
https://forum.lazarus.freepascal.org/index.php/topic,34645.0.html

**Comment by levone1** [comment]
> Maybe you can ask for support here https://forum.lazarus.freepascal.org/index.php/topic,34645.0.html

Thanks for your help. .. BTW - what's a good cli arg to launch with higher dpi?

**Comment by levone1** [comment]
> Maybe you can ask for support here https://forum.lazarus.freepascal.org/index.php/topic,34645.0.html

So, I was able to get all packages built and Cudatext running on SailfishOS, using --ws qt5, but my problem now is that the keyboard won't pop up when I go into text entry/edit. May not be an issue with Cudatext, but wondered if you might have some idea about it.
Sailfish uses maliit for native keyboard. I'm sure there's Sailfish-specific coding in native apps to make it work,  but I have built and installed other qt apps, (Cantata, Tea editor, and QTFM), and they all bring up the Sailfish keyboard when in a text field. Maybe there's some code I could add or something...

![Screenshot_20220619_001](https://user-images.githubusercontent.com/43003405/174465716-11634d21-10f7-42ec-8258-078e957da10d.png)
![Screenshot_20220619_002](https://user-images.githubusercontent.com/43003405/174465718-44bb4c84-16e9-421f-9cd1-0cc9e00d96dc.png)

**Comment by Alexey-T** [comment]
Maybe ATsynedit needs some special support for this, like reacting to some event. what must it support?

PS. No CLI arguments for higher DPI, sorry.

**Comment by Alexey-T** [comment]
Did you have enabled this IFDEF in atsynedit.pas?

```
    {$ifdef GTK2_IME_CODE}
    procedure WM_GTK_IM_COMPOSITION(var Message: TLMessage); message LM_IM_COMPOSITION;
    {$endif}
```

**Comment by levone1** [comment]
> Did you have enabled this IFDEF in atsynedit.pas?
> 
> ```
>     {$ifdef GTK2_IME_CODE}
>     procedure WM_GTK_IM_COMPOSITION(var Message: TLMessage); message LM_IM_COMPOSITION;
>     {$endif}
> ```

Not sure if 'enabled', but I rebuilt without that code, and no change. Something else I can test?

**Comment by Alexey-T** [comment]
If you build w/o that code, then build with that define - in the project properties, add define "GTK2_IME_CODE" (or add it in the begin of file atsynedit.pas)

**Comment by levone1** [comment]
> If you build w/o that code, then build with that define - in the project properties, add define "GTK2_IME_CODE" (or add it in the begin of file atsynedit.pas)

ok... This is already at the beginning 
`
{$ifdef LCLGTK2}
  {$if (LCL_FULLVERSION >= 2030000)}
    {$define GTK2_IME_CODE}
  {$endif}
{$endif}`

Is that it, or should I add something else?

**Comment by Alexey-T** [comment]
1. That line enables GTK2_IME_CODE only in new Lazarus>=2.3.
2. If that line don't help, I don't know how to enable toe onscreen keyboard in your OS...

**Comment by levone1** [comment]
> 1. That line enables GTK2_IME_CODE only in new Lazarus>=2.3.
> 
>     2. If that line don't help, I don't know how to enable toe onscreen keyboard in your OS...

ok, thanks... Btw - did you catch the that I built all packages with qt5 widget set? I actually don't have native gtk on Sailfish, but I   can symlink to libs in lxc container to build...

**Comment by Alexey-T** [comment]
if you use qt5, then GTK2_IME_CODE define don't work at all.

**Comment by levone1** [comment]
> if you use qt5, then GTK2_IME_CODE define don't work at all.

Any ideas what code it is in the other apps that makes my qt keyboard work, that maybe could be added?

Thanks for your work

**Comment by Alexey-T** [comment]
Try to make new app, which has the ATsynedit control on a form. If you tested only CudaText before . Sorry, I don’t know. Ask at the Lazarus forum, the same about synedit component. What part of synedit enables the keyboard?

**Comment by levone1** [comment]
Just in case it's helpful to you...  I had the same experience building on my Linux Mint desktop that I had on my Debian Sid mobile lxc container.  All attempts to build through any fpc/Lazarus gui/ide failed with some kind of error, (varied depending on the version, source, install method, etc.), but building succeeded when running lazbuild command in terminal for each of the dependency packages, ([whatever].lpk), and then going to Cudatext directory and using lazbuild command on cudatext.lpi

**Comment by Alexey-T** [comment]
OK, but that don't help us to find why onscreen keyboard cannot be run

**Comment by psemiletov** [comment]
Maybe some checking of the focused control fails. I don't know (

**Comment by Alexey-T** [comment]
I repeat. Did you try the empty Lazarus app?

- app with one SynEdit control
- app with one ATSynEdit control

do they get onscr keyboard?

**Comment by levone1** [comment]
> I repeat. Did you try the empty Lazarus app?
> 
>     * app with one SynEdit control
> 
>     * app with one ATSynEdit control
> 
> 
> do they get onscr keyboard?

sorry - no. It is the same in Lazarus app, no keyboard.

**Comment by Alexey-T** [comment]
okay. so can you report this - to the Lazarus bugtracker or better to the forum first?
what ppl say?
https://forum.lazarus.freepascal.org/index.php?board=13.0

**Comment by Alexey-T** [comment]
closing the topic. Because atsynedit_cmp is not related.
